language: java
sudo: required
dist: trusty
install: true

arch: 
- 'arm64'
- 'amd64'
addons:
  apt:
    packages:
      - dpkg
  chrome: stable

jdk:
- oraclejdk8
- openjdk8

before_install:
- chmod +x test/run.sh
- chmod +x test/after_success.sh
 
script:
- test/run.sh

after_success: 
- test/after_success.sh
